{{- if and .Values.spec.config_files .Values.spec.config_files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-files
  labels:
    {{- include "app-chart.metadataLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.spec.config_files }}
  {{ $value.file_name }}: {{ $value.content | b64enc }}
  {{- end }}
{{- end }}
