intent: kubernetes_cluster
flavor: aws-eks
alias-flavors:
- default
version: '0.1'
clouds:
- aws
title: EKS Cluster with Auto Mode support
description: A Kubernetes EKS cluster module with auto mode enabled by default and
  all necessary configurations preset.
allow_skipping_module_on_selective_release: false
spec:
  type: object
  x-ui-order:
  - cluster
  - secret_copier
  - tags
  properties:
    secret_copier:
      type: object
      title: Secret Copier
      description: Configuration for the Secret Copier.
      x-ui-toggle: false
      properties:
        enabled:
          type: boolean
          title: Enabled
          description: Enable secret copier.
          default: true
        values:
          type: object
          title: Values
          description: Values to pass to the secret copier.
          default: {}
          x-ui-yaml-editor: true
    cluster:
      type: object
      title: Cluster
      description: Configuration for the EKS cluster.
      x-ui-toggle: false
      properties:
        kubernetes_version:
          type: string
          title: Kubernetes Version
          description: Version of Kubernetes to use for the EKS cluster.
          default: '1.31'
        cluster_endpoint_public_access:
          type: boolean
          title: Cluster Endpoint Public Access
          description: Whether the Amazon EKS public API server endpoint is enabled.
          default: true
          x-ui-overrides-only: true
        cluster_endpoint_private_access:
          type: boolean
          title: Cluster Endpoint Private Access
          description: Whether the Amazon EKS private API server endpoint is enabled.
          default: true
          x-ui-overrides-only: true
        cluster_endpoint_public_access_cidrs:
          type: array
          title: Cluster Endpoint Public Access CIDRs
          description: List of CIDR blocks which can access the Amazon EKS public
            API server endpoint.
          default:
          - 0.0.0.0/0
          x-ui-overrides-only: true
        cluster_endpoint_private_access_cidrs:
          type: array
          title: Cluster Endpoint Private Access CIDRs
          description: List of CIDR blocks which can access the Amazon EKS private
            API server endpoint.
          default:
          - 0.0.0.0/0
          x-ui-overrides-only: true
        cloudwatch_log_group_retention_in_days:
          type: number
          title: Cloudwatch Log Group Retention In Days
          description: Retention period for the Cloudwatch log group.
          default: 90
        cluster_enabled_log_types:
          type: array
          title: Cluster Enabled Log Types
          description: List of log types to enable for the EKS cluster.
          default:
          - api
          - audit
          - authenticator
          x-ui-overrides-only: true
        enable_cluster_encryption:
          type: boolean
          title: Enable Cluster Encryption
          description: Enable encryption for the cluster secrets.
          default: true
        default_reclaim_policy:
          type: string
          title: Default Reclaim Policy
          description: Default reclaim policy for the EKS cluster.
          default: Delete
          x-ui-overrides-only: true
          enum:
          - Delete
          - Retain
        kms:
          type: object
          title: KMS
          description: Configuration for the KMS key.
          x-ui-toggle: false
          x-ui-overrides-only: true
          properties:
            deletion_window_in_days:
              title: Deletion Window
              description: Waiting period in days after which kms keys are deleted
              type: number
              minimum: 7
              maximum: 30
              default: 7
              x-ui-error-message: Deletion window must be between 7 and 30
            enable_rotation:
              title: Enable Rotation for KMS
              description: Specifies whether key rotation is enabled
              type: boolean
              default: false
            rotation_period_in_days:
              title: Rotation Period for KMS in days
              description: Specifies Rotation Period for KMS in days
              type: number
              default: 90
              minimum: 1
              maximum: 365
              x-ui-visible-if:
                field: spec.cluster.kms_keys.enable_rotation
                values:
                - true
      required:
      - kubernetes_version
    tags:
      type: object
      title: Tags
      description: Tags to apply to the EKS cluster.
      x-ui-toggle: false
      x-ui-yaml-editor: true
  required:
  - cluster
inputs:
  network_details:
    type: '@facets/aws-vpc-details'
    displayName: Network
    default:
      resource_type: network
      resource_name: default
  cloud_account:
    type: '@outputs/cloud_account'
    displayName: Cloud Account
    description: The AWS Cloud Account where the EKS cluster will be created
    optional: false
    providers:
    - aws
    - aws4
    - aws5
    - aws593
outputs:
  attributes.k8s_details:
    type: '@outputs/aws_eks'
    title: Kubernetes Cluster Output
    description: The output for the Kubernetes cluster
    providers:
      kubernetes:
        source: hashicorp/kubernetes
        version: 2.17.0
        attributes:
          host: cluster.auth.host
          token: cluster.auth.token
          cluster_ca_certificate: cluster.auth.cluster_ca_certificate
      helm:
        source: hashicorp/helm
        version: 2.8.0
        attributes:
          kubernetes:
            host: cluster.auth.host
            token: cluster.auth.token
            cluster_ca_certificate: cluster.auth.cluster_ca_certificate
      kubernetes-alpha:
        source: hashicorp/kubernetes-alpha
        version: 0.6.0
        attributes:
          host: cluster.auth.host
          cluster_ca_certificate: cluster.auth.cluster_ca_certificate
          token: cluster.auth.token
sample:
  kind: kubernetes_cluster
  flavor: aws-eks
  alias-flavors:
  - default
  version: '0.1'
  metadata:
    name: eks-cluster
  spec:
    cluster:
      kubernetes_version: '1.31'
      cluster_endpoint_public_access: true
      cluster_endpoint_private_access: false
      cluster_endpoint_public_access_cidrs:
      - 0.0.0.0/0
      cluster_endpoint_private_access_cidrs:
      - 0.0.0.0/0
    secret_copier:
      enabled: true
      values:
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
    tags: {}
